In [ ]:
import sqlite3
import pandas as pd

# Conexión en memoria (se pierde al cerrar el notebook)
conn = sqlite3.connect(":restaurante.db:")
cur = conn.cursor() #objeto para ejecutar comandos de SQL

def query(sql, params=()):
    """Ejecuta un SELECT y devuelve un DataFrame para verlo bonito."""
    return pd.read_sql_query(sql, conn, params=params)

def run(sql, params=()):
    """Ejecuta INSERT/UPDATE/DELETE/DDL y hace commit."""
    cur.execute(sql, params)
    conn.commit()
    print("OK ->", sql.strip().splitlines()[0], "...")

Ejercicio 1

Una cadena de restaurantes necesita registrar en su base de datos el menú de platillos que ofrece. Crea
una tabla llamada comida que cumpla con las siguientes especificaciones:

In [ ]:
cur.executescript('''
DROP TABLE IF EXISTS comida;

CREATE TABLE comida (
    id_platillo INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    categoria VARCHAR(50),
    precio DECIMAL(6,2) NOT NULL,
    disponible BOOLEAN DEFAULT TRUE
);
''')
conn.commit()
print("Tabla recreada con columna 'disponible' correcta")

Tabla recreada con columna 'disponible' correcta

In [ ]:
# INSERT INTO

run('''
INSERT INTO comida (id_platillo, nombre, categoria, precio, disponible) VALUES
    (1, 'Tacos al pastor', 'plato fuerte', 85.00, 1),
    (2, 'Ensalada César', 'entrada', 65.50, 1),
    (3, 'Flan napolitano', 'postre', 45.00, 1);
''')

query("SELECT * FROM comida")

OK -> INSERT INTO comida (id_platillo, nombre, categoria, precio, disponible) VALUES ...

   id_platillo           nombre     categoria  precio  disponible
0            1  Tacos al pastor  plato fuerte    85.0           1
1            2   Ensalada César       entrada    65.5           1
2            3  Flan napolitano        postre    45.0           1

In [ ]:
# SELECT

query("SELECT * FROM comida")

   id_platillo           nombre     categoria  precio  disponible
0            1  Tacos al pastor  plato fuerte    85.0           1
1            2   Ensalada César       entrada    65.5           1
2            3  Flan napolitano        postre    45.0           1

In [ ]:
# UPDATE

run("UPDATE comida SET precio = precio * 1.10 WHERE categoria = 'plato fuerte';")

query("SELECT id_platillo, nombre, precio FROM comida WHERE categoria = 'plato fuerte'")

OK -> UPDATE comida SET precio = precio * 1.10 WHERE categoria = 'plato fuerte'; ...

   id_platillo           nombre  precio
0            1  Tacos al pastor    93.5

In [ ]:
# DELETE

run("DELETE FROM comida WHERE categoria = 'postre';")

query("SELECT * FROM comida")

OK -> DELETE FROM comida WHERE categoria = 'postre'; ...

   id_platillo           nombre     categoria  precio  disponible
0            1  Tacos al pastor  plato fuerte    93.5           1
1            2   Ensalada César       entrada    65.5           1

Ejemplo 2 — Escuela (tabla alumnos)

Una escuela quiere registrar la información básica de sus alumnos.

In [ ]:
cur.executescript('''
DROP TABLE IF EXISTS alumnos;

CREATE TABLE alumnos (
    id_alumno INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    grado VARCHAR(10),
    edad INT NOT NULL,
    promedio DECIMAL(4,2) DEFAULT 0.0
);
''')
conn.commit()
print("Tabla 'alumnos' creada")

Tabla 'alumnos' creada

In [ ]:
# INSERT INTO
run('''
INSERT INTO alumnos (nombre, grado, edad, promedio) VALUES
    ('Ana López', '3ro A', 9, 8.5),
    ('Carlos Ruiz', '5to B', 11, 7.8),
    ('María Sánchez', '3ro A', 8, 9.2);
''')

query("SELECT * FROM alumnos")

OK -> INSERT INTO alumnos (nombre, grado, edad, promedio) VALUES ...

   id_alumno         nombre  grado  edad  promedio
0          1      Ana López  3ro A     9       8.5
1          2    Carlos Ruiz  5to B    11       7.8
2          3  María Sánchez  3ro A     8       9.2

In [ ]:
# UPDATE
run("UPDATE alumnos SET promedio = promedio + 0.3 WHERE grado = '3ro A';")

query("SELECT id_alumno, nombre, grado, promedio FROM alumnos WHERE grado = '3ro A'")

OK -> UPDATE alumnos SET promedio = promedio + 0.3 WHERE grado = '3ro A'; ...

   id_alumno         nombre  grado  promedio
0          1      Ana López  3ro A       8.8
1          3  María Sánchez  3ro A       9.5

In [ ]:
# DELETE
run("DELETE FROM alumnos WHERE nombre = 'Carlos Ruiz';")

query("SELECT * FROM alumnos")

OK -> DELETE FROM alumnos WHERE nombre = 'Carlos Ruiz'; ...

   id_alumno         nombre  grado  edad  promedio
0          1      Ana López  3ro A     9       8.8
1          3  María Sánchez  3ro A     8       9.5

Ejemplo 3 — Tiendita escolar

La tiendita de la escuela necesita llevar el control de los productos que vende.

In [ ]:
cur.executescript('''
DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
    id_producto INTEGER PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    tipo VARCHAR(30),
    precio DECIMAL(6,2) NOT NULL,
    existencia INT DEFAULT 0
);
''')
conn.commit()
print("Tabla 'productos' creada")

Tabla 'productos' creada

In [ ]:
# INSERT INTO
run('''
INSERT INTO productos (nombre, tipo, precio, existencia) VALUES
    ('Papas fritas', 'snack', 15.00, 30),
    ('Jugo de manzana', 'bebida', 12.50, 25),
    ('Chocolate', 'dulce', 10.00, 40);
''')

query("SELECT * FROM productos")

OK -> INSERT INTO productos (nombre, tipo, precio, existencia) VALUES ...

   id_producto           nombre    tipo  precio  existencia
0            1     Papas fritas   snack    15.0          30
1            2  Jugo de manzana  bebida    12.5          25
2            3        Chocolate   dulce    10.0          40

In [ ]:
# UPDATE
run("UPDATE productos SET existencia = existencia - 10 WHERE nombre = 'Chocolate';")

query("SELECT id_producto, nombre, existencia FROM productos WHERE nombre = 'Chocolate'")

OK -> UPDATE productos SET existencia = existencia - 10 WHERE nombre = 'Chocolate'; ...

   id_producto     nombre  existencia
0            3  Chocolate          30

In [ ]:
# DELETE
run("DELETE FROM productos WHERE nombre = 'Jugo de manzana';")

query("SELECT * FROM productos")

OK -> DELETE FROM productos WHERE nombre = 'Jugo de manzana'; ...

   id_producto        nombre   tipo  precio  existencia
0            1  Papas fritas  snack      15          30
1            3     Chocolate  dulce      10          30